

spring:
  application:
    name: demo-service
  datasource:
    url: jdbc:mysql://localhost:3306/tododb?useSSL=false&serverTimezone=UTC
    username: javi
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080